document.writeln('<div class="TY-leftNav">');
document.writeln('    <div class="TY-leftInfor">');
document.writeln('       <div class="partPic"><i class="pic" style=""></i><div class="infor"><i>系统管理员</i><i>admin123</i></div></div>');
document.writeln('       <div class="partIco"><a href="" target="_blank" title="前台页面"></a><a class="backtop" href="" target="" title="退出登录"></a></div>');
document.writeln('    </div>');
document.writeln('    <div class="leftNav">');
document.writeln('       <div class="uInfo hide"><a class="hp" style=""></a></div>');
document.writeln('       <div class="bars">');
document.writeln('          <div onclick="menuLeft(this)" index="0" class="home cur"><div><i></i>基本设置</div></div>');
document.writeln('          <div onclick="toggleLeft(this)" class="toggle"><div><i></i>展开收起</div></div>');
document.writeln('       </div>');
document.writeln('    </div>');
document.writeln('    <div class="leftLink mCustomScrollbar _mCS_1">');
document.writeln('       <div class="mCustomScrollBox mCS-leftnav" id="mCSB_1"  style="position:relative; height:100%; overflow:hidden; max-width:100%;">');
document.writeln('          <div class="mCSB_container" style="position:relative; top:0;">');
document.writeln('             <div class="menus"></div>');
document.writeln('                    <div menu="">');
document.writeln('                               <a class="nav nav_select" onclick="secMenu(this)"><i class="ico"></i><i	class="ico-tg"></i><i>用户分类</i></a>');
document.writeln('                               <dl>');
document.writeln('                                  <dd>');
document.writeln('                                    <a target="page" href="./hospital.html"><i class="ico"></i><i>医院用户</i></a>');
document.writeln('                                  </dd>');
document.writeln('                                  <dd>');
document.writeln('                                    <a target="page" href="./channel.html"><i class="ico"></i><i>渠道用户</i></a>');
document.writeln('                                  </dd>');
document.writeln('                                  <dd>');
document.writeln('                                    <a target="page" href="./employees.html"><i class="ico"></i><i>员工列表</i></a>');
document.writeln('                                  <dd>');
document.writeln('                               </dl>');
document.writeln('                               <a class="nav nav_select" onclick="secMenu(this)"><i class="ico"></i><i class="ico-tg"></i><i>客户服务</i></a>');
document.writeln('                               <dl>');
document.writeln('                                   <dd>');
document.writeln('                                     <a target="page" href="./repair.html"><i class="ico"></i><i>客户报修单</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                     <a target="page" href="./employeesGongdan.html"><i class="ico"></i><i>员工报修单</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                     <a target="page" href="./progress.html"><i class="ico"></i><i>派单列表</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                     <a target="page" href="./product.html"><i class="ico"></i><i>产品信息</i></a>');
document.writeln('                                   <dd>');
// document.writeln('                                   <dd>');
// document.writeln('                                     <a target="page" href="./productclass.html"><i class="ico"></i><i>产品分类</i></a>');
// document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                      <a target="page" href="./accessories.html"><i class="ico"></i><i>配件购买</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                      <a target="page" href="./feedback.html"><i class="ico"></i><i>意见反馈</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                      <a target="page" href="./customer.html"><i class="ico"></i><i>客户管理</i></a>');
document.writeln('                                   <dd>');
document.writeln('                                   <dd>');
document.writeln('                                      <a target="page" href="./knowledge.html"><i class="ico"></i><i>维修知识</i></a>');
document.writeln('                                   <dd>');
document.writeln('                               </dl>');
document.writeln('                               <a class="nav nav_select" onclick="secMenu(this)"><i class="ico"></i><i	class="ico-tg"></i><i>日志管理</i></a>');
document.writeln('                               <dl>');
document.writeln('                                   <dd>');
document.writeln('                                      <a target="page" href="./log.html"><i class="ico"></i><i>操作日志</i></a>');
document.writeln('                                   <dd>');
document.writeln('                               </dl>');
document.writeln('                          </div>');
document.writeln('                     </div>');
document.writeln('                </div>');
document.writeln('           </div>');
document.writeln('     </div>');